import type { CSSProperties } from 'react'

export const browserStyles: Record<string, CSSProperties> = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: '1.5rem',
    border: '1px solid var(--border)',
    borderRadius: 14,
    marginTop: '1.75rem',
    background: 'var(--surface)',
    color: 'var(--text-h)',
    textAlign: 'left',
    boxShadow: 'var(--shadow)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '0.75rem',
    borderBottom: '1px solid var(--border)',
  },
  breadcrumbs: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.15rem',
    padding: '0.55rem 0.85rem',
    background: 'var(--code-bg)',
    border: '1px solid var(--accent-border)',
    borderRadius: 999,
  },
  breadcrumbItem: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  breadcrumbSep: {
    color: 'var(--accent-strong)',
    margin: '0 0.2rem',
    fontWeight: 600,
  },
  breadcrumbButton: {
    padding: '0.2rem 0.5rem',
    border: 'none',
    background: 'transparent',
    color: 'var(--accent-strong)',
    cursor: 'pointer',
    fontSize: '0.9rem',
    borderRadius: 4,
    fontWeight: 500,
  },
  breadcrumbButtonCurrent: {
    color: 'var(--text-h)',
    fontWeight: 700,
    cursor: 'default',
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  locationHint: {
    color: 'var(--text)',
    fontSize: '0.9rem',
  },
  code: {
    fontFamily: 'var(--mono)',
    fontSize: '0.85rem',
    background: 'var(--code-bg)',
    padding: '0.1rem 0.4rem',
    borderRadius: 4,
    color: 'var(--text-h)',
    border: '1px solid var(--border)',
  },
  row: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  input: {
    flex: '1 1 200px',
    padding: '0.55rem 0.85rem',
    border: '1px solid var(--border)',
    borderRadius: 8,
    fontSize: '0.95rem',
    background: 'var(--surface)',
    color: 'var(--text-h)',
    outlineColor: 'var(--accent)',
  },
  browser: {
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '0.85rem 1rem',
    background: 'var(--code-bg)',
    minHeight: 120,
  },
  sectionTitle: {
    margin: '0 0 0.75rem',
    fontWeight: 700,
    color: 'var(--text-h)',
    fontSize: '0.95rem',
    letterSpacing: '0.01em',
  },
  groupLabel: {
    margin: '0 0 0.4rem',
    fontSize: '0.72rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
    color: 'var(--accent-strong)',
  },
  entryList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  entryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    width: '100%',
    padding: '0.6rem 0.85rem',
    border: '1px solid var(--border)',
    borderRadius: 8,
    background: 'var(--surface)',
    color: 'var(--text-h)',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '0.95rem',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease, transform 0.05s',
  },
  entryButtonActive: {
    borderColor: 'var(--accent-border)',
    background: 'var(--accent-bg)',
    boxShadow: '0 0 0 3px var(--accent-bg)',
  },
  fileRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    padding: '0.6rem 0.85rem',
    border: '1px solid var(--border)',
    borderRadius: 8,
    background: 'var(--surface)',
    color: 'var(--text-h)',
    fontSize: '0.95rem',
  },
  entryIcon: {
    fontSize: '1.15rem',
    flexShrink: 0,
  },
  entryName: {
    flex: 1,
    fontWeight: 500,
    wordBreak: 'break-all',
  },
  entryMeta: {
    color: 'var(--text)',
    fontSize: '0.82rem',
    flexShrink: 0,
  },
  emptyHint: {
    margin: 0,
    color: 'var(--text)',
    fontStyle: 'italic',
  },
  loadingHint: {
    color: 'var(--accent-strong)',
    fontWeight: 600,
    opacity: 0.9,
  },
  primaryButton: {
    padding: '0.55rem 1.1rem',
    background: 'var(--cta)',
    color: '#ffffff',
    border: '1px solid var(--cta)',
    borderRadius: 999,
    cursor: 'pointer',
    fontWeight: 700,
    letterSpacing: '0.01em',
    boxShadow: '0 6px 14px -6px rgba(255, 127, 80, 0.6)',
  },
  secondaryButton: {
    padding: '0.45rem 1rem',
    background: 'var(--surface)',
    color: 'var(--accent-strong)',
    border: '1px solid var(--accent-border)',
    borderRadius: 999,
    cursor: 'pointer',
    fontWeight: 600,
  },
  error: {
    color: '#b91c1c',
    margin: 0,
    padding: '0.6rem 0.85rem',
    background: 'rgba(185, 28, 28, 0.08)',
    border: '1px solid rgba(185, 28, 28, 0.2)',
    borderRadius: 8,
  },
  info: {
    color: '#0c8a95',
    margin: 0,
    padding: '0.6rem 0.85rem',
    background: 'var(--accent-bg)',
    border: '1px solid var(--accent-border)',
    borderRadius: 8,
  },
  playerWrap: {
    border: '1px solid var(--accent-border)',
    borderRadius: 12,
    padding: '0.85rem',
    background:
      'linear-gradient(180deg, var(--code-bg) 0%, var(--surface) 100%)',
    boxShadow: 'var(--shadow)',
  },
  playerHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    marginBottom: '0.6rem',
  },
  playerTitle: {
    margin: 0,
    fontWeight: 700,
    color: 'var(--text-h)',
    wordBreak: 'break-all',
  },
  video: {
    width: '100%',
    maxHeight: 'min(70vh, 720px)',
    borderRadius: 10,
    background: '#000',
    boxShadow: '0 12px 30px -12px rgba(12, 46, 74, 0.45)',
  },
  previewImage: {
    width: '100%',
    maxHeight: 'min(70vh, 820px)',
    borderRadius: 10,
    objectFit: 'contain',
    background: 'var(--surface)',
    boxShadow: '0 12px 30px -12px rgba(12, 46, 74, 0.35)',
  },
  previewFrame: {
    width: '100%',
    minHeight: 520,
    borderRadius: 10,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
  },
}
