import type { CSSProperties } from 'react'

export const browserStyles: Record<string, CSSProperties> = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: '1.5rem',
    border: '1px solid var(--border)',
    borderRadius: 8,
    marginTop: '2rem',
    background: 'var(--bg)',
    color: 'var(--text-h)',
    textAlign: 'left',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  breadcrumbs: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.15rem',
    padding: '0.5rem 0.75rem',
    background: 'var(--code-bg)',
    border: '1px solid var(--border)',
    borderRadius: 6,
  },
  breadcrumbItem: {
    display: 'inline-flex',
    alignItems: 'center',
  },
  breadcrumbSep: {
    color: 'var(--text)',
    margin: '0 0.2rem',
  },
  breadcrumbButton: {
    padding: '0.2rem 0.35rem',
    border: 'none',
    background: 'transparent',
    color: 'var(--accent)',
    cursor: 'pointer',
    fontSize: '0.9rem',
    borderRadius: 4,
  },
  breadcrumbButtonCurrent: {
    color: 'var(--text-h)',
    fontWeight: 600,
    cursor: 'default',
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  locationHint: {
    color: 'var(--text)',
    fontSize: '0.9rem',
  },
  code: {
    fontFamily: 'var(--mono)',
    fontSize: '0.85rem',
    background: 'var(--code-bg)',
    padding: '0.1rem 0.35rem',
    borderRadius: 4,
    color: 'var(--text-h)',
  },
  row: {
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  input: {
    flex: '1 1 200px',
    padding: '0.5rem 0.75rem',
    border: '1px solid var(--border)',
    borderRadius: 6,
    fontSize: '0.95rem',
    background: 'var(--bg)',
    color: 'var(--text-h)',
  },
  browser: {
    border: '1px solid var(--border)',
    borderRadius: 6,
    padding: '0.75rem 1rem',
    background: 'var(--code-bg)',
    minHeight: 120,
  },
  sectionTitle: {
    margin: '0 0 0.75rem',
    fontWeight: 600,
    color: 'var(--text-h)',
  },
  groupLabel: {
    margin: '0 0 0.35rem',
    fontSize: '0.8rem',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    color: 'var(--text)',
  },
  entryList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
  },
  entryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    width: '100%',
    padding: '0.55rem 0.75rem',
    border: '1px solid var(--border)',
    borderRadius: 6,
    background: 'var(--bg)',
    color: 'var(--text-h)',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '0.95rem',
  },
  entryButtonActive: {
    borderColor: 'var(--accent-border)',
    background: 'var(--accent-bg)',
  },
  fileRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.55rem 0.75rem',
    border: '1px solid var(--border)',
    borderRadius: 6,
    background: 'var(--bg)',
    color: 'var(--text-h)',
    fontSize: '0.95rem',
  },
  entryIcon: {
    fontSize: '1.1rem',
    flexShrink: 0,
  },
  entryName: {
    flex: 1,
    fontWeight: 500,
    wordBreak: 'break-all',
  },
  entryMeta: {
    color: 'var(--text)',
    fontSize: '0.85rem',
    flexShrink: 0,
  },
  emptyHint: {
    margin: 0,
    color: 'var(--text)',
    fontStyle: 'italic',
  },
  loadingHint: {
    color: 'var(--text)',
    fontWeight: 400,
    opacity: 0.7,
  },
  primaryButton: {
    padding: '0.5rem 1rem',
    background: 'var(--accent)',
    color: '#ffffff',
    border: '1px solid var(--accent)',
    borderRadius: 6,
    cursor: 'pointer',
    fontWeight: 600,
  },
  secondaryButton: {
    padding: '0.4rem 0.9rem',
    background: 'var(--bg)',
    color: 'var(--text-h)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    cursor: 'pointer',
    fontWeight: 500,
  },
  error: {
    color: '#b91c1c',
    margin: 0,
  },
  info: {
    color: '#047857',
    margin: 0,
  },
  playerWrap: {
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '0.75rem',
    background: 'var(--code-bg)',
  },
  playerHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    marginBottom: '0.5rem',
  },
  playerTitle: {
    margin: 0,
    fontWeight: 600,
    color: 'var(--text-h)',
    wordBreak: 'break-all',
  },
  video: {
    width: '100%',
    maxHeight: 'min(70vh, 720px)',
    borderRadius: 6,
    background: '#000',
  },
}
